export {default as Home} from "../pages/Home";
export {default as Profile} from "../pages/Profile";
export {default as MyProjectNav } from "./MyProjectNav";
export {default as Overview} from "../pages/MyGroup/Overview";
export {default as ScholarDetails} from "../pages/MyGroup/ScholarDetails";
export {default as Thesis} from "../pages/Thesis/Thesis";
export {default as ThesisDetails} from "../pages/Thesis/ThesisDetails";
export {default as MyProject} from "../pages/MyProject/MyProject";
export {default as MyProjectOverview} from "../pages/MyProject/MyProjectOverview";
export {default as MyProjectForums} from "../pages/MyProject/MyProjectForums";
export {default as MyProjectActivityPlan} from "../pages/MyProject/MyProjectActivityPlan";
export {default as MyProjectFinal} from "../pages/MyProject/MyProjectFinal";
export {default as RPS} from "../pages/RPS";
export {default as CE} from "../pages/CE";